---
title: Lapidify
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  books:
    title: Books
    output: true
    permalink: "/books/:title"
  category:
    title: Category
    output: true
    permalink: "/category/:name"
  facts:
    title: Facts
    output: true
    permalink: "/facts/:title"
  lapidify:
    title: Lapidify
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  videos:
    title: Videos
    output: true
defaults:
- scope:
    path: ''
    type: books
  values:
    layout: book
- scope:
    path: ''
    type: category
  values:
    layout: category
- scope:
    path: ''
    type: facts
  values:
    layout: facts
name: Lapidify
description: We take you to the awesome world of knowledge. Read contents from almost
  all ypur favorite topics including science, technology, facts etc. Enjoy!
baseurl: ''
authorbox: disabled
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-figure
highlighter: none
disqus: demowebsite
include:
- _pages
mailchimp-list: ''
permalink: "/:title/"
lazyimages: disabled
paginate_path: "/blog/page:num/"
paginate: 6
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
    category: "/cat/:name/"
exclude:
- changelog.md
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock
